name: Deploy Weather App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Debug (Temporary)
      - name: Check Secrets
        run: |
          if [ -z "${{ secrets.HOST }}" ]; then
            echo "❌ HOST secret is missing"
            exit 1
          fi

          if [ -z "${{ secrets.USERNAME }}" ]; then
            echo "❌ USERNAME secret is missing"
            exit 1
          fi

          if [ -z "${{ secrets.PORT }}" ]; then
            echo "❌ PORT secret is missing"
            exit 1
          fi

          if [ -z "${{ secrets.SSH_KEY }}" ]; then
            echo "❌ SSH_KEY secret is missing"
            exit 1
          fi

          echo "✅ All Secrets Found"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/weather-app

            git pull origin main

            cd backend

            source venv/bin/activate

            pip install -r requirements.txt

            sudo systemctl restart weather

            sudo systemctl restart nginx

            echo "Deployment Successful"
